apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: talhahussain913/mern-server:server-v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: server-config
        - secretRef:
            name: mongo-secret