apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort  # Makes the client accessible from outside cluster
  selector:
    app: client   # Matches the label in client deployment
  ports:
    - protocol: TCP
      port: 80     # Service port
      targetPort: 80  # Container port
      nodePort: 30000  # Access at <minikube-ip>:30000